/*
    MERTCAN TAKIL 05140000643
    SERKAY YÜKSEL 05140000686
    SAFA ORHAN 05140000627
 */
package telefonrehberi;

import java.io.FilePermission;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.AccessController;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Metox
 */
public class Arayuz extends javax.swing.JFrame {

    /**
     */
    Rehber rehber = new Rehber("rehber.txt");
    public Arayuz() throws IOException {
        initComponents();
        rehber.AdSoyadlariYazdir(TerstenYazdirma.getText()=="Z-A",Kisiler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        EkleAdSoyad = new javax.swing.JTextField();
        EkleNumaralar = new javax.swing.JTextField();
        EkleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Aranan = new javax.swing.JTextField();
        KisiSil = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Kisiler = new java.awt.List();
        KisiBilgi = new java.awt.List();
        TerstenYazdirma = new javax.swing.JButton();
        AraButon = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        EkleAdSoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleAdSoyadActionPerformed(evt);
            }
        });

        EkleNumaralar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleNumaralarActionPerformed(evt);
            }
        });

        EkleButton.setText("Kişi Ekle");
        EkleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EkleButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Kişiler");

        jLabel2.setText("Kişi Bilgisi");

        jLabel3.setText("Ad Soyad");

        jLabel4.setText("Telefon Numaraları(virgülle ayır)");

        Aranan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ArananKeyTyped(evt);
            }
        });

        KisiSil.setText("Kişiyi Sil");
        KisiSil.setEnabled(false);
        KisiSil.setFocusPainted(false);
        KisiSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KisiSilMouseClicked(evt);
            }
        });

        Kisiler.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                KisilerItemStateChanged(evt);
            }
        });

        TerstenYazdirma.setText("A-Z");
        TerstenYazdirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TerstenYazdirmaMouseClicked(evt);
            }
        });

        AraButon.setText("Ara");
        AraButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AraButonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KisiBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AraButon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Aranan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EkleNumaralar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(68, 68, 68))
                        .addComponent(EkleAdSoyad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EkleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TerstenYazdirma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KisiSil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Kisiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EkleAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EkleNumaralar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EkleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Aranan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AraButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KisiBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KisiSil)
                            .addComponent(jLabel1)
                            .addComponent(TerstenYazdirma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kisiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EkleNumaralarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleNumaralarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EkleNumaralarActionPerformed

    private void EkleAdSoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleAdSoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EkleAdSoyadActionPerformed

    private void EkleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EkleButtonMouseClicked
        rehber.KisiEkle(EkleAdSoyad.getText()+","+EkleNumaralar.getText());
        rehber.AdSoyadlariYazdir(TerstenYazdirma.getText()=="Z-A",Kisiler);
    }//GEN-LAST:event_EkleButtonMouseClicked

    private void KisilerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_KisilerItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            KisiSil.setEnabled(true);
            rehber.NumaralarYazdir(KisiBilgi, Kisiler.getSelectedItem());
            
        }
        else if(evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED){
            KisiSil.setEnabled(false);
            Kisiler.removeAll();
        }
    }//GEN-LAST:event_KisilerItemStateChanged

    private void KisiSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KisiSilMouseClicked
        rehber.KisiSil(Kisiler);
        rehber.AdSoyadlariYazdir(TerstenYazdirma.getText()=="Z-A",Kisiler);
        KisiBilgi.removeAll();
    }//GEN-LAST:event_KisiSilMouseClicked

    private void TerstenYazdirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TerstenYazdirmaMouseClicked
        TerstenYazdirma.setText(TerstenYazdirma.getText()=="Z-A"?"A-Z":"Z-A");
        rehber.AdSoyadlariYazdir(TerstenYazdirma.getText()=="Z-A",Kisiler);
    }//GEN-LAST:event_TerstenYazdirmaMouseClicked

    private void ArananKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ArananKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ArananKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
          try {
            rehber.Kaydet();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Arayuz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Arayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void AraButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AraButonMouseClicked
        if(Aranan.getText().equals(""))
            rehber.AdSoyadlariYazdir(TerstenYazdirma.getText()=="Z-A",Kisiler);
        else
            rehber.AraVeYazdir(Kisiler, Aranan.getText());
    }//GEN-LAST:event_AraButonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Arayuz().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Arayuz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AraButon;
    private javax.swing.JTextField Aranan;
    private javax.swing.JTextField EkleAdSoyad;
    private javax.swing.JButton EkleButton;
    private javax.swing.JTextField EkleNumaralar;
    private java.awt.List KisiBilgi;
    private javax.swing.JButton KisiSil;
    private java.awt.List Kisiler;
    private javax.swing.JButton TerstenYazdirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
